version: '3.4'

networks:
  multilayer-cache-network:

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - multilayer-cache-network
    
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_USER=sa
      - MSSQL_SA_PASSWORD=Multil@yer123!
    ports:
      - "1433:1433"
    networks:
      - multilayer-cache-network

  MemCache.productservice.api:
    image: ${DOCKER_REGISTRY-}MemCacheproductserviceapi
    build:
      context: .
      dockerfile: MemCache.ProductService.API/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - ms-sql-server
    environment:
      - Port=4000
      - RabbitMqConfiguration=rabbitmq
      - DbConnectionString=Data Source=ms-sql-server;Initial Catalog = ProductServiceDB;Persist Security Info=True;Integrated Security=False;User ID =sa; Password=Multil@yer123!;Connect Timeout=15000;MultipleActiveResultSets=true;TrustServerCertificate=True;
    networks:
      - multilayer-cache-network

